# Generated by Django 3.1.4 on 2020-12-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=75)),
                ('final_score', models.CharField(max_length=75)),
                ('event_schedule', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=75)),
                ('team_type', models.CharField(max_length=75)),
                ('team_rank', models.IntegerField()),
                ('team_value', models.IntegerField()),
                ('team_rerolls', models.IntegerField()),
                ('fan_factor', models.IntegerField()),
                ('league_name', models.CharField(max_length=75)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('position', models.CharField(max_length=75)),
                ('movement', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('armor_value', models.IntegerField()),
                ('skills', models.CharField(max_length=75)),
                ('cost', models.IntegerField()),
                ('history', models.CharField(max_length=75)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.coach')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.team')),
            ],
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuffleapi.event')),
            ],
        ),
    ]
